<?xml version="1.0"?>
<package format="3">
  <name>turtlebot3_parking_mission</name>
  <version>0.0.0</version>
  <description>Parking mission logic for TurtleBot3</description>
  <maintainer email="andy@example.com">andy</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
